"""init

Revision ID: f046fd0bd4b7
Revises: 
Create Date: 2025-11-18 00:11:06.371142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f046fd0bd4b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_excel_upload_logs_id', table_name='excel_upload_logs')
    op.drop_index('ix_excel_upload_logs_status', table_name='excel_upload_logs')
    op.drop_index('ix_excel_upload_logs_uploaded_at', table_name='excel_upload_logs')
    op.drop_table('excel_upload_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excel_upload_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('uploaded_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('status', mysql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'), nullable=False),
    sa.Column('total_rows', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('successful_rows', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed_rows', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('error_message', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_excel_upload_logs_uploaded_at', 'excel_upload_logs', ['uploaded_at'], unique=False)
    op.create_index('ix_excel_upload_logs_status', 'excel_upload_logs', ['status'], unique=False)
    op.create_index('ix_excel_upload_logs_id', 'excel_upload_logs', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###
